import { NextRequest, NextResponse } from 'next/server'
import ExcelJS from 'exceljs'
import { createClient } from '@/lib/supabase/server'

export const runtime = 'nodejs'

export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient()

    // Verify authentication
    const { data: { user }, error: authError } = await supabase.auth.getUser()
    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    // Get user role for RBAC
    const { data: profile } = await supabase
      .from('profiles')
      .select('role')
      .eq('id', user.id)
      .single()

    if (profile?.role === 'viewer') {
      return NextResponse.json(
        { error: 'Viewers cannot export data. Contact your administrator.' },
        { status: 403 }
      )
    }

    const body = await request.json()
    const { title, sheets, metadata } = body

    if (!title || !sheets || !Array.isArray(sheets)) {
      return NextResponse.json(
        { error: 'Title and sheets array are required' },
        { status: 400 }
      )
    }

    // Create workbook
    const workbook = new ExcelJS.Workbook()
    workbook.creator = 'Ask Finance'
    workbook.created = new Date()
    workbook.modified = new Date()

    // Add metadata
    workbook.title = title
    workbook.subject = 'Financial Report'
    workbook.keywords = 'finance, report, analysis'

    for (const sheetConfig of sheets) {
      const { name, type, data, columns } = sheetConfig

      const worksheet = workbook.addWorksheet(name, {
        properties: { tabColor: { argb: '3B82F6' } },
        pageSetup: { paperSize: 9, orientation: 'landscape' },
      })

      if (type === 'data' && data && Array.isArray(data)) {
        // Add column headers
        const headers = columns || (data.length > 0 ? Object.keys(data[0]) : [])

        // Style for header row
        const headerRow = worksheet.addRow(headers.map((h: string) => formatHeader(h)))
        headerRow.font = { bold: true, color: { argb: 'FFFFFF' } }
        headerRow.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: '1E3A8A' },
        }
        headerRow.alignment = { vertical: 'middle', horizontal: 'center' }
        headerRow.height = 25

        // Add data rows
        for (const row of data) {
          const rowData = headers.map((h: string) => {
            const value = row[h]
            // Format numbers appropriately
            if (typeof value === 'number') {
              return value
            }
            return value
          })
          const dataRow = worksheet.addRow(rowData)

          // Alternate row colors
          if (data.indexOf(row) % 2 === 1) {
            dataRow.fill = {
              type: 'pattern',
              pattern: 'solid',
              fgColor: { argb: 'F3F4F6' },
            }
          }
        }

        // Auto-fit columns
        worksheet.columns.forEach((column, index) => {
          let maxLength = headers[index]?.length || 10
          data.forEach(row => {
            const value = row[headers[index]]
            if (value) {
              const length = String(value).length
              if (length > maxLength) maxLength = length
            }
          })
          column.width = Math.min(maxLength + 2, 50)
        })

        // Add filters
        worksheet.autoFilter = {
          from: { row: 1, column: 1 },
          to: { row: 1, column: headers.length },
        }

        // Freeze header row
        worksheet.views = [{ state: 'frozen', ySplit: 1 }]

      } else if (type === 'summary') {
        // Summary sheet with key metrics
        worksheet.addRow([title])
        worksheet.mergeCells('A1:D1')
        const titleCell = worksheet.getCell('A1')
        titleCell.font = { bold: true, size: 16 }
        titleCell.alignment = { horizontal: 'center' }

        worksheet.addRow([])
        worksheet.addRow(['Generated:', new Date().toLocaleString()])
        worksheet.addRow(['Generated by:', 'Ask Finance AI'])
        worksheet.addRow([])

        if (data) {
          if (typeof data === 'object' && !Array.isArray(data)) {
            for (const [key, value] of Object.entries(data)) {
              worksheet.addRow([formatHeader(key), value])
            }
          }
        }

      } else if (type === 'chart') {
        // Note: ExcelJS chart support is limited
        // Add chart data and instructions
        worksheet.addRow(['Chart Data'])
        worksheet.getCell('A1').font = { bold: true, size: 14 }

        if (data && data.data && Array.isArray(data.data)) {
          const chartData = data.data
          const keys = chartData.length > 0 ? Object.keys(chartData[0]) : []

          worksheet.addRow(keys)
          for (const row of chartData) {
            worksheet.addRow(keys.map(k => row[k]))
          }
        }
      }
    }

    // Generate buffer
    const buffer = await workbook.xlsx.writeBuffer()

    // Log export
    await supabase.from('usage_logs').insert({
      user_id: user.id,
      action: 'export_excel',
      details: {
        title,
        sheetsCount: sheets.length,
        timestamp: new Date().toISOString(),
      },
    })

    // Return file
    return new NextResponse(buffer, {
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'Content-Disposition': `attachment; filename="${sanitizeFilename(title)}.xlsx"`,
      },
    })

  } catch (error) {
    console.error('Excel export error:', error)
    return NextResponse.json(
      { error: 'Failed to generate Excel file' },
      { status: 500 }
    )
  }
}

function formatHeader(key: string): string {
  return key
    .replace(/([A-Z])/g, ' $1')
    .replace(/_/g, ' ')
    .replace(/^./, str => str.toUpperCase())
    .trim()
}

function sanitizeFilename(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9\s-_]/g, '')
    .replace(/\s+/g, '_')
    .substring(0, 50)
}
