import { NextRequest, NextResponse } from 'next/server'
import PptxGenJS from 'pptxgenjs'
import { createClient } from '@/lib/supabase/server'

export const runtime = 'nodejs'

export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient()

    // Verify authentication
    const { data: { user }, error: authError } = await supabase.auth.getUser()
    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    // Get user role for RBAC
    const { data: profile } = await supabase
      .from('profiles')
      .select('role')
      .eq('id', user.id)
      .single()

    if (profile?.role === 'viewer') {
      return NextResponse.json(
        { error: 'Viewers cannot export data. Contact your administrator.' },
        { status: 403 }
      )
    }

    const body = await request.json()
    const { title, slides, author } = body

    if (!title || !slides || !Array.isArray(slides)) {
      return NextResponse.json(
        { error: 'Title and slides array are required' },
        { status: 400 }
      )
    }

    // Create presentation
    const pptx = new PptxGenJS()
    pptx.title = title
    pptx.subject = 'Financial Report'
    pptx.author = author || 'Ask Finance AI'
    pptx.company = 'Ask Finance'

    // Define master slide
    pptx.defineSlideMaster({
      title: 'MASTER_SLIDE',
      background: { color: 'FFFFFF' },
      objects: [
        // Header bar
        {
          rect: {
            x: 0, y: 0, w: '100%', h: 0.7,
            fill: { color: '1E3A8A' }
          }
        },
        // Footer
        {
          text: {
            text: 'Ask Finance | Confidential',
            options: {
              x: 0.5, y: 5.2, w: 4, h: 0.3,
              fontSize: 8, color: '666666'
            }
          }
        },
        // Page number
        {
          text: {
            text: 'Page',
            options: {
              x: 8.5, y: 5.2, w: 1, h: 0.3,
              fontSize: 8, color: '666666'
            }
          }
        },
      ],
    })

    // Add title slide
    const titleSlide = pptx.addSlide()
    titleSlide.addText(title, {
      x: 0.5, y: 2, w: 9, h: 1.5,
      fontSize: 36, bold: true, color: '1E3A8A',
      align: 'center', valign: 'middle'
    })
    titleSlide.addText(new Date().toLocaleDateString('en-US', {
      year: 'numeric', month: 'long', day: 'numeric'
    }), {
      x: 0.5, y: 3.5, w: 9, h: 0.5,
      fontSize: 14, color: '666666',
      align: 'center'
    })
    titleSlide.addText('Generated by Ask Finance AI', {
      x: 0.5, y: 4, w: 9, h: 0.5,
      fontSize: 12, color: '999999',
      align: 'center'
    })

    // Add content slides
    for (const slideConfig of slides) {
      const slide = pptx.addSlide({ masterName: 'MASTER_SLIDE' })

      // Add slide title
      slide.addText(slideConfig.title, {
        x: 0.5, y: 0.15, w: 9, h: 0.5,
        fontSize: 18, bold: true, color: 'FFFFFF'
      })

      const { type, content, bullets, chartData, tableData } = slideConfig

      if (type === 'content' && content) {
        // Text content slide
        slide.addText(content, {
          x: 0.5, y: 1, w: 9, h: 4,
          fontSize: 14, color: '333333',
          valign: 'top'
        })
      }

      if (type === 'content' && bullets && Array.isArray(bullets)) {
        // Bullet points
        const bulletText = bullets.map((b: string) => ({
          text: b,
          options: { bullet: { type: 'bullet' as const }, fontSize: 14 }
        }))
        slide.addText(bulletText, {
          x: 0.5, y: 1, w: 9, h: 4,
          color: '333333', valign: 'top'
        })
      }

      if (type === 'chart' && chartData) {
        // Chart slide
        const { chartType, data, xAxisKey, yAxisKeys } = chartData

        if (data && Array.isArray(data) && data.length > 0) {
          // Prepare chart data for pptxgenjs
          const labels = data.map(d => String(d[xAxisKey] || ''))
          const chartDataSeries = (yAxisKeys || []).map((key: string) => ({
            name: formatLabel(key),
            labels,
            values: data.map(d => Number(d[key]) || 0)
          }))

          const pptxChartType = mapChartType(chartType)

          slide.addChart(pptxChartType, chartDataSeries, {
            x: 0.5, y: 1.2, w: 9, h: 4,
            showLegend: true,
            legendPos: 'b',
            showTitle: false,
            chartColors: ['3B82F6', '10B981', 'F59E0B', 'EF4444', '8B5CF6'],
          })
        }
      }

      if (type === 'table' && tableData) {
        // Table slide
        const { columns, rows } = tableData

        if (columns && rows && Array.isArray(rows)) {
          const tableRows = [
            columns.map((col: string) => ({
              text: formatLabel(col),
              options: { bold: true, fill: { color: '1E3A8A' }, color: 'FFFFFF' }
            })),
            ...rows.map((row: any) =>
              columns.map((col: string) => ({
                text: formatValue(row[col]),
                options: { fill: { color: 'F3F4F6' } }
              }))
            )
          ]

          slide.addTable(tableRows, {
            x: 0.5, y: 1.2, w: 9,
            fontSize: 10,
            border: { pt: 0.5, color: 'CCCCCC' },
            align: 'center',
            valign: 'middle',
          })
        }
      }

      if (type === 'summary') {
        // Summary slide with key metrics
        if (content && typeof content === 'object') {
          const metrics = Object.entries(content)
          const rows = metrics.map(([key, value]) => [
            { text: formatLabel(key), options: { bold: true } },
            { text: formatValue(value), options: { align: 'right' as const } }
          ])

          slide.addTable(rows as any, {
            x: 1, y: 1.5, w: 8,
            fontSize: 14,
            border: { pt: 0, color: 'FFFFFF' },
          })
        }
      }
    }

    // Generate buffer
    const buffer = await pptx.write({ outputType: 'nodebuffer' })

    // Log export
    await supabase.from('usage_logs').insert({
      user_id: user.id,
      action: 'export_powerpoint',
      details: {
        title,
        slidesCount: slides.length + 1,
        timestamp: new Date().toISOString(),
      },
    })

    // Return file
    return new NextResponse(buffer as unknown as BodyInit, {
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'Content-Disposition': `attachment; filename="${sanitizeFilename(title)}.pptx"`,
      },
    })

  } catch (error) {
    console.error('PowerPoint export error:', error)
    return NextResponse.json(
      { error: 'Failed to generate PowerPoint file' },
      { status: 500 }
    )
  }
}

function formatLabel(key: string): string {
  return key
    .replace(/([A-Z])/g, ' $1')
    .replace(/_/g, ' ')
    .replace(/^./, str => str.toUpperCase())
    .trim()
}

function formatValue(value: any): string {
  if (value === null || value === undefined) return '-'
  if (typeof value === 'number') {
    if (Math.abs(value) >= 1000000) {
      return `$${(value / 1000000).toFixed(1)}M`
    }
    if (Math.abs(value) >= 1000) {
      return `$${(value / 1000).toFixed(0)}K`
    }
    return value.toLocaleString()
  }
  return String(value)
}

function sanitizeFilename(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9\s-_]/g, '')
    .replace(/\s+/g, '_')
    .substring(0, 50)
}

function mapChartType(type: string): any {
  const mapping: Record<string, any> = {
    'line': 'line',
    'bar': 'bar',
    'pie': 'pie',
    'area': 'area',
    'composed': 'bar',
  }
  return mapping[type] || 'bar'
}
